services:
  sreeifier:
    build: ./python
    environment:
      - PORT=50051
    ports:
        - 50051:50051

  proxy:
    build: .
    depends_on:
      - sreeifier
    ports:
      - 8080:8080
    volumes:
      - ~/.config/gcloud/application_default_credentials.json:/tmp/cred.json
    environment:
      - INSECURE=true
      - SREEIFIER_SERVER=sreeifier:50051
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/cred.json
