name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-proxy:
    name: Build Proxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorise GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/baileybutler-syd/sreekipedia:${{ github.sha }} .
          docker push gcr.io/baileybutler-syd/sreekipedia:${{ github.sha }}

  deploy-proxy:
    name: Deploy Proxy
    runs-on: ubuntu-latest
    needs:
      - build-proxy
      - build-sreeifier

    steps:
      - name: Authorise GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: sreekipedia
          image: gcr.io/baileybutler-syd/sreekipedia:${{ github.sha }}
          region: asia-southeast1
          flags: "--min-instances=0 --max-instances=100 --allow-unauthenticated"
          env_vars: |
            SREEIFIER_SERVER=sreeifier-vvgwyvu7bq-as.a.run.app:443

  build-sreeifier:
    name: Build Sreeifier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authorise GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3

      - name: Configure Docker
        run: |
          gcloud --quiet auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/baileybutler-syd/sreeifier:${{ github.sha }} ./python
          docker push gcr.io/baileybutler-syd/sreeifier:${{ github.sha }}

  deploy-sreeifier:
    name: Deploy Sreeifier
    runs-on: ubuntu-latest
    needs:
      - build-sreeifier

    steps:
      - name: Authorise GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: sreeifier
          image: gcr.io/baileybutler-syd/sreeifier:${{ github.sha }}
          region: asia-southeast1
          flags: "--min-instances=0 --max-instances=100 --use-http2 --allow-unauthenticated"
